import React, { useCallback, useLayoutEffect, useMemo, useRef, useState } from 'react';
import './KubernetesLifecycleReel.css';

type Color = 'blue' | 'purple' | 'orange' | 'green';
type Side = 'left' | 'right' | 'top' | 'bottom';
type Link = { id: string; from: string; to: string; label: string; color: Color; stage?: number; static?: boolean; a: Side; b: Side; lt?: number };

const total = 28;
const links: Link[] = [
  { id:'devkub',from:'developer',to:'kubectl',label:'CLI • kubectl apply -f ...',color:'blue',stage:0,a:'right',b:'left' },
  { id:'kubapi',from:'kubectl',to:'apiserver',label:'HTTPS Kubernetes API • POST /apis/apps/v1/...',color:'blue',stage:1,a:'bottom',b:'top' },
  { id:'apietcd',from:'apiserver',to:'etcd',label:'etcd v3 / gRPC • persist cluster state',color:'purple',stage:8,a:'bottom',b:'top',lt:.78 },
  { id:'depapi',from:'deploy',to:'apiserver',label:'HTTPS WATCH Deployment • POST / PATCH ReplicaSet',color:'purple',stage:9,a:'top',b:'bottom',lt:.30 },
  { id:'rsapi',from:'rs',to:'apiserver',label:'HTTPS WATCH ReplicaSet • POST Pod objects',color:'purple',stage:10,a:'top',b:'bottom',lt:.33 },
  { id:'schapi',from:'scheduler',to:'apiserver',label:'HTTPS WATCH Pending Pod • POST Binding',color:'purple',stage:11,a:'top',b:'bottom',lt:.26 },
  { id:'kubeapi',from:'kubelet',to:'apiserver',label:'HTTPS WATCH assigned Pods ↔ PATCH Pod status',color:'orange',stage:12,a:'left',b:'right' },
  { id:'kubecsi',from:'kubelet',to:'csi',label:'CSI gRPC • stage / publish volume',color:'orange',stage:13,a:'right',b:'left' },
  { id:'csivolume',from:'csi',to:'volume',label:'mount volume',color:'orange',stage:14,a:'top',b:'bottom' },
  { id:'kubecri',from:'kubelet',to:'cri',label:'CRI gRPC • PullImage / RunPodSandbox / CreateContainer',color:'orange',stage:15,a:'right',b:'left' },
  { id:'cricni',from:'cri',to:'cni',label:'CNI ADD • configure Pod sandbox network',color:'orange',stage:16,a:'top',b:'bottom' },
  { id:'cnipod',from:'cni',to:'pod',label:'setup Pod networking • Pod IP',color:'orange',stage:17,a:'right',b:'left' },
  { id:'cripod',from:'cri',to:'pod',label:'start containers after CNI setup',color:'orange',stage:18,a:'right',b:'left' },
  { id:'volpod',from:'volume',to:'pod',label:'mounted /data',color:'orange',stage:19,a:'right',b:'left' },
  { id:'podstatus',from:'pod',to:'statusBox',label:'readiness + container state → kubelet status',color:'orange',stage:20,a:'bottom',b:'right' },
  { id:'browserproxy',from:'browser',to:'proxy',label:'HTTPS application request',color:'blue',stage:21,a:'right',b:'left' },
  { id:'proxylb',from:'proxy',to:'lb',label:'HTTPS / TCP forward • proxy / WAF policy',color:'blue',stage:22,a:'right',b:'left' },
  { id:'lbing',from:'lb',to:'ingress',label:'L4 / L7 forward to Ingress / Gateway',color:'blue',stage:23,a:'bottom',b:'top' },
  { id:'ingsvc',from:'ingress',to:'service',label:'HTTP route • host/path → Service',color:'blue',stage:24,a:'right',b:'left' },
  { id:'svcdp',from:'service',to:'svcData',label:'Service + EndpointSlice → datapath rules',color:'green',stage:25,a:'bottom',b:'top' },
  { id:'dppod',from:'svcData',to:'readyPod',label:'Ready endpoint • application traffic → Pod IP',color:'green',stage:26,a:'right',b:'left' },
  { id:'samepod',from:'readyPod',to:'pod',label:'same logical Pod • now Ready',color:'green',stage:27,a:'bottom',b:'top' },
];
const actions = ['Developer / CI → kubectl • run deployment command','kubectl → Kube-APIServer • HTTPS Kubernetes API','API Server • Authentication','API Server • Authorization','API Server • Mutating Admission','API Server • Schema Validation','API Server • Validating Admission','API Server • Persist object','Kube-APIServer → etcd • persist cluster state','Deployment Controller ↔ API Server • WATCH Deployment / create ReplicaSet','ReplicaSet Controller ↔ API Server • WATCH ReplicaSet / create Pod','Scheduler ↔ API Server • WATCH Pending Pod / POST Binding','kubelet ↔ Kube-APIServer • WATCH assigned Pod','kubelet → CSI • stage / publish volume','CSI → Volume • mount volume on Node','kubelet → CRI • pull image / create Pod sandbox','CRI → CNI • CNI ADD for Pod sandbox','CNI → Pod • network namespace, Pod IP, eth0 and routes ready','CRI → Pod • start containers after network setup','Volume → Pod • mounted /data','Pod / kubelet → API Server • report Running / Ready status','User Browser → Proxy / WAF • HTTPS application request','Proxy / WAF → Load Balancer • forward HTTPS/TCP','Load Balancer → Ingress / Gateway • L4/L7 forwarding','Ingress / Gateway → Service • host/path routing','Service → Service Datapath • program/select Ready endpoint','Service Datapath → Ready Pod • application traffic to Pod IP','Ready Pod ↔ Pod lifecycle view • same Pod is now Ready'];
const colors: Record<Color,string> = { blue:'#78a9dc', purple:'#b894cd', orange:'#e7a66d', green:'#75ba8f' };

function anchor(root: HTMLElement, node: HTMLElement, side: Side) { const r=node.getBoundingClientRect(), d=root.getBoundingClientRect(), x=r.left-d.left, y=r.top-d.top; if(side==='left') return {x,y:y+r.height/2}; if(side==='right') return {x:x+r.width,y:y+r.height/2}; if(side==='top') return {x:x+r.width/2,y}; return {x:x+r.width/2,y:y+r.height}; }
function pathFor(s:{x:number;y:number},t:{x:number;y:number},a:Side,b:Side) { const ah=a==='left'||a==='right', bh=b==='left'||b==='right'; if(ah&&bh){const m=(s.x+t.x)/2;return `M${s.x},${s.y} C${m},${s.y} ${m},${t.y} ${t.x},${t.y}`;} if(!ah&&!bh){const m=(s.y+t.y)/2;return `M${s.x},${s.y} C${s.x},${m} ${t.x},${m} ${t.x},${t.y}`;} return `M${s.x},${s.y} C${ah?(s.x+t.x)/2:s.x},${ah?s.y:(s.y+t.y)/2} ${bh?(s.x+t.x)/2:t.x},${bh?t.y:(s.y+t.y)/2} ${t.x},${t.y}`; }
function Component({id,className='',children}:{id:string;className?:string;children:React.ReactNode}) { return <div id={id} className={`v13-component ${className}`}>{children}</div>; }
function Node({id,className='',children}:{id:string;className?:string;children:React.ReactNode}) { return <div id={id} className={`v13-node ${className}`}>{children}</div>; }

export function KubernetesLifecycleReel() {
 const root=useRef<HTMLDivElement>(null); const [stage,setStage]=useState(0); const [playing,setPlaying]=useState(true); const [speed,setSpeed]=useState(1550); const [paths,setPaths]=useState<Record<string,string>>({});
 const current=links.find(x=>x.stage===stage); const networkReady=stage>=17; const running=stage>=18; const volumeMounted=stage>=19; const ready=stage>=20;
 const draw=useCallback(()=>{const host=root.current;if(!host)return;const next:Record<string,string>={}; for(const l of links){const f=host.querySelector<HTMLElement>(`#${l.from}`),t=host.querySelector<HTMLElement>(`#${l.to}`);if(f&&t)next[l.id]=pathFor(anchor(host,f,l.a),anchor(host,t,l.b),l.a,l.b);}setPaths(next);},[]);
 useLayoutEffect(()=>{draw();const observer=new ResizeObserver(draw);if(root.current)observer.observe(root.current);return()=>observer.disconnect();},[draw]);
 const stageDelay=stage>=21?Math.max(1900,Math.round(speed*1.25)):speed; const trafficDotDuration=Math.max(.35,(stageDelay-80)/2000); useLayoutEffect(()=>{if(!playing)return;const id=window.setTimeout(()=>setStage(s=>(s+1)%total),stageDelay);return()=>window.clearTimeout(id);},[stage,playing,stageDelay]);
 const active=useMemo(()=>new Set(current?[current.from,current.to]:stage>=2&&stage<=7?['apiserver']:[]),[current,stage]);
 const nodeClass=(id:string, extra='')=>`${extra} ${active.has(id)?'active-node':''} ${ready && ['readyPod','pod'].includes(id)?'green-node':''}`;
 const labelPosFor=(link:Link)=>{if(!root.current)return null;const f=root.current.querySelector<HTMLElement>(`#${link.from}`),t=root.current.querySelector<HTMLElement>(`#${link.to}`);if(!f||!t)return null;const a=anchor(root.current,f,link.a),b=anchor(root.current,t,link.b);return link.id==='csivolume'?{left:a.x-96,top:(a.y+b.y)/2}:{left:(a.x+b.x)/2,top:(a.y+b.y)/2-28};}; const pos=current?labelPosFor(current):null;
 const go=(next:number)=>{setPlaying(false);setStage((next+total)%total);};
 return <div className="v13-viewport"><section className="k8sReelSource v13" aria-label="Kubernetes Request Lifecycle">
  <header className="v13-header"><div className="v13-logo">☸</div><div><h2>Kubernetes Request Lifecycle</h2><p>External/Edge tách khỏi cluster; Control Plane và Data Plane có đường đi độc lập, label chỉ hiện ở đường đang active.</p></div><div className="v13-controls"><button onClick={()=>go(stage-1)}>◀</button><button className="primary" onClick={()=>setPlaying(x=>!x)}>{playing?'⏸ Pause':'▶ Play'}</button><button onClick={()=>go(stage+1)}>▶</button><button onClick={()=>{setStage(0);setPlaying(true)}}>↻ Replay</button><button className="test" onClick={()=>{setStage(21);setPlaying(true)}}>▶ TEST 22→28</button><select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value="2800">0.5x</option><option value="1550">1x</option><option value="820">2x</option></select><b className="v13-counter">{stage+1} / 28</b></div></header>
  <div className="v13-action"><b>Current action:</b><span>{actions[stage]}</span>{stage>=21&&<small>● TRAFFIC RUNNING</small>}<i>{stage>=21?`User traffic ${stage-20}/7`:''}</i></div>
  <div className="v13-diagram" ref={root}><svg className="v13-svg" viewBox={`0 0 ${root.current?.clientWidth||1} ${root.current?.clientHeight||1}`} preserveAspectRatio="none" aria-hidden="true"><defs>{(Object.keys(colors) as Color[]).map(c=><marker key={c} id={`v13-arrow-${c}`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10z" fill={colors[c]}/></marker>)}</defs>{links.map(l=><path key={l.id} className={`v13-link ${l.color} ${l.static?'static':''} ${current?.id===l.id?'active':''}`} d={paths[l.id]} markerEnd={`url(#v13-arrow-${l.color})`}/>)}{current&&paths[current.id]&&<circle key={current.id} className={`v13-traffic-dot ${current.color}`} r="5"><animateMotion dur={`${trafficDotDuration}s`} repeatCount="indefinite" path={paths[current.id]}/></circle>}</svg>{links.filter(l=>l.static).map(l=>{const staticPos=labelPosFor(l);return staticPos&&<div key={`${l.id}-label`} className={`v13-line-label static ${l.color}`} style={staticPos}>{l.label}</div>})}{current&&pos&&<div className={`v13-line-label ${current.color}`} style={{left:pos.left,top:pos.top}}>{current.label}</div>}
   <div className="v13-top-grid"><section className="v13-top-lane"><b>Management / Deployment Path</b><Node id="developer" className={nodeClass('developer','dev')}>👨‍💻<strong>Developer / CI</strong><small>deploy workload</small></Node><Node id="kubectl" className={nodeClass('kubectl','kubectl')}>☸<strong>kubectl</strong><small>kubeconfig + local validation</small></Node></section><section className="v13-top-lane"><b>External / Edge — Application Traffic Path</b><Node id="browser" className={nodeClass('browser','browser')}>🧑‍💻<strong>User Browser</strong><small>application request</small></Node><Node id="proxy" className={nodeClass('proxy','proxy')}>🛡️<strong>Proxy / WAF</strong><small>edge / reverse proxy</small></Node><Node id="lb" className={nodeClass('lb','lb')}>⚖️<strong>Load Balancer</strong><small>forward into cluster</small></Node></section></div>
   <div className="v13-planes"><section className="v13-plane"><h3 className="cphead">CONTROL PLANE <small>API hub + state + reconciliation + scheduling</small></h3><div className="v13-cp-body"><div className="api-wrap"><Component id="apiserver" className={nodeClass('apiserver','apiserver')}><h4>☸ Kube-APIServer</h4><p>Central API hub — mọi control component đọc/ghi cluster state qua Kubernetes API.</p><div className="api-grid">{[['🔐','Authentication','token / x509 / OIDC'],['🛡️','Authorization','RBAC / ABAC'],['🪝','Mutating Admission','mutate payload'],['✓','Schema Validation','object schema'],['📋','Validating Admission','policy allow / deny'],['🗄️','Persist','write object to etcd']].map(([i,n,d],index=0)=><div className={`api-step ${stage===index+2?'sa':stage>index+2?'sd':''}`} key={n}><span>{i}</span><b>{n}</b><small>{d}</small></div>)}</div></Component></div><div className="cp-connector-zone"/><div className="cp-bottom"><Component id="etcd" className={nodeClass('etcd')}><div className="db">🛢️</div><h4>etcd</h4><p>authoritative cluster state</p></Component><Component id="deploy" className={nodeClass('deploy')}><h4>⚙ Deployment Controller</h4><p>WATCH Deployment</p><p>POST / PATCH ReplicaSet</p><span className="badge">kube-controller-manager</span></Component><Component id="rs" className={nodeClass('rs')}><h4>⚙ ReplicaSet Controller</h4><p>WATCH ReplicaSet</p><p>POST Pod objects</p><span className="badge">kube-controller-manager</span></Component><Component id="scheduler" className={nodeClass('scheduler')}><h4>▦ Scheduler</h4><p>WATCH unscheduled Pods</p><p>Filter + Score Node</p><p>POST Binding</p></Component></div><p className="cp-note">Deployment Controller, ReplicaSet Controller và Scheduler không gọi trực tiếp nhau. Chúng WATCH / POST / PATCH resource qua Kube-APIServer.</p></div></section>
   <section className="v13-plane"><h3 className="dphead">DATA PLANE <small>Ingress + Service traffic + Worker Node execution</small></h3><div className="v13-dp-body"><div className="traffic-entry"><Component id="ingress" className={nodeClass('ingress')}><h4>🌐 Ingress / Gateway Controller</h4><p>host / path routing</p><p>TLS termination tùy topology</p></Component><Component id="service" className={nodeClass('service')}><h4>🔀 Service (logical)</h4><p>stable virtual endpoint</p><p>select Ready endpoints</p></Component></div><div className="worker"><b className="worker-title">🖥 Worker Node: worker-1</b><small className="worker-sub">Data Plane</small><div className="user-lane"><i>A. User Traffic Lane — chỉ dùng sau khi Pod Ready</i><Component id="svcData" className={nodeClass('svcData')}><h4>🔧 Service Datapath</h4><p>kube-proxy / eBPF</p><p>programmed from Service + EndpointSlice</p></Component><div className="ready-endpoint-label">Ready endpoint<br/>→ Pod IP</div><Component id="readyPod" className={nodeClass('readyPod')}><h4>📦 Ready Pod</h4><p>application receives traffic</p><p>same Pod shown below</p></Component></div><div className="pod-lane"><i>B. Pod Lifecycle Lane — kubelet chuẩn bị và chạy Pod</i><Component id="kubelet" className={nodeClass('kubelet')}><h4>☸ kubelet</h4><p>WATCH Pods assigned to worker-1</p><p>reconcile desired Pod state</p></Component><div className="stack-col"><Component id="volume" className={nodeClass('volume')}><h4>💽 Volume</h4><p>node-mounted storage</p></Component><Component id="csi" className={nodeClass('csi')}><h4>💾 CSI</h4><p>stage / publish volume</p></Component><Component id="cni" className={nodeClass('cni')}><h4>🌐 CNI</h4><p>Pod sandbox network + IP</p></Component><Component id="cri" className={nodeClass('cri')}><h4>📦 CRI</h4><p>containerd / CRI-O</p><p>pull image + start containers</p></Component></div><Component id="pod" className={nodeClass('pod')}><div className="podcap"><span>Pod</span><span>{running?'Running':'Pending'}</span></div><div className="container">📦 App Container</div><div className="container">📦 Sidecar / Init nếu có</div>{networkReady&&<div className="network-status"><b>Network: READY ✓</b><span>Pod IP: 10.244.1.15</span><span>Interface: eth0</span><span>Routes: configured</span></div>}{volumeMounted&&<div className="volume-status">💽 Volume: <b>/data</b></div>}<div className="status">{ready?'● Ready':'○ Not Ready'}</div></Component></div><Component id="statusBox" className={nodeClass('statusBox')}><h4>↩ Pod Status</h4><p>kubelet PATCHes status</p><p>Running / Ready / Failed</p></Component><div className="node-note"><b>Node interfaces:</b> CSI / CNI / CRI là interface/plugin trên Node, không nằm bên trong Pod. User traffic lane và Pod lifecycle lane là hai luồng khác nhau.</div></div></div></section></div>
  </div><div className="v13-legend"><b>Line:</b><span>Blue Kubernetes API / HTTP(S)</span><span>Purple controller / scheduler</span><span>Orange node execution</span><span>Green Ready-Pod service traffic</span></div>
 </section></div>;
}
